---
- name: Copy threshold script to host Block
  when:
    - enable_threshold_script | default(false) | bool
  tags: update_threshold_script
  block:
    - name: Create hooks directory to scripts
      ansible.builtin.file:
        path: "{{ zrepl_config_path }}/hooks"
        state: directory
        mode: "755"

    - name: Copy Threshold Script to host
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        backup: "{{ item.backup }}"
      with_items:
        - { src: "zfs_threshold_check.sh", dest: "{{ zrepl_config_path }}/hooks",
            mode: "750", owner: "root", group: "root", backup: false }

- name: Copy zrepl.yml template to host
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    backup: "{{ item.backup }}"
    # validate: /usr/bin/zrepl configcheck %s
  with_items:
    - { src: "zrepl.yml.j2", dest: "{{ zrepl_config_path }}/zrepl.yml", mode: "644", owner: "root", group: "root", backup: false }
  notify:
    - Restart zrepl
  tags: update_config

- name: Copy PKI Certificates to host
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    backup: "{{ item.backup }}"
  with_items:
    - { src: "pki/{{ zrepl_tls_ca_crt_name }}", dest: "{{ zrepl_config_path }}/{{ zrepl_tls_ca_crt_name }}",
        mode: "640", owner: "root", group: "root", backup: true }
    - { src: "pki/issued/{{ zrepl_tls_cert_name }}", dest: "{{ zrepl_config_path }}/{{ zrepl_tls_cert_name }}",
        mode: "640", owner: "root", group: "root", backup: true }
    - { src: "pki/private/{{ zrepl_tls_private_key_name }}", dest: "{{ zrepl_config_path }}/{{ zrepl_tls_private_key_name }}",
        mode: "600", owner: "root", group: "root", backup: true }
  notify:
    - Restart zrepl
  tags: update_pki

- name: Validate Job Filesystems
  ansible.builtin.command:
    zrepl test filesystems --job snapjob_{{ item.name }} --all
  register: cmd_output
  changed_when: cmd_output.rc != 0
  loop: "{{ zrepl_snapjobs }}"
  loop_control:
    label: "snapjob_{{ item.name }}"
  tags: test_filesystem_jobs
